import type { Metadata } from 'next'

export const siteConfig: Metadata = {
  title: 'Jarvis AI',
  description: 'A Modern SaaS AI Platform Build with Next.js 14.',
  keywords: [
    'reactjs',
    'nextjs',
    'netlify',
    'react',
    'jarvis-ai',
    'artifical-intelligence',
    'shadcn',
    'shadcn-ui',
    'radix-ui',
    'cn',
    'clsx',
    'saas',
    'aiven',
    'sonner',
    'zustand',
    'zod',
    'mysql',
    'sql',
    'lucide-react',
    'crisp-chat',
    'postcss',
    'prettier',
    'react-dom',
    'tailwindcss',
    'tailwindcss-animate',
    'ui/ux',
    'js',
    'javascript',
    'typescript',
    'eslint',
    'html',
    'css',
  ] as Array<string>,
  authors: {
    name: 'Aftab Rehan',
    url: 'https://github.com/aftabrehan',
  },
} as const
